on:
  push:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare short commit hash
        id: vars
        run: echo "git_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: "version=${{ steps.vars.outputs.git_sha_short }}"
          platforms: linux/amd64
          push: true
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.git_sha_short }}

      - name: Generate .env for Compose
        run: |
          cat > .env <<EOF
          CF_DNS_API_TOKEN=${{ secrets.CF_DNS_API_TOKEN }}
          TG_BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          TG_PUBLIC_PREFIX=${{ secrets.TG_PUBLIC_PREFIX }}
          EOF

      - uses: humbertocrispim/ssh-docker-compose-action@v1.0.0
        name: Remote Deployment with Docker-Compose
        with:
          ssh_host: public.akiba.space
          ssh_private_key: ${{ secrets.AKIBA_PUBLIC_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.AKIBA_PUBLIC_SSH_USER }}
          docker_compose_prefix: ${{ github.event.repository.name }}
          docker_compose_filename: compose.yml
          pull: true